import{i as m,a as y,S as u}from"./assets/vendor-DimZQZwF.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const g=document.getElementById("search-form"),f=document.getElementById("gallery"),d=document.getElementById("loader"),h=document.querySelector(".load-more-container"),n=document.getElementById("load-more");n.textContent="Load more";n.style.display="none";h.appendChild(n);const b="45874849-b987a1554bc8f853b4bc2ad05";let l=1,i="";g.addEventListener("submit",async a=>{a.preventDefault(),i=document.getElementById("search-query").value.trim(),i?(l=1,f.innerHTML="",n.style.display="none",await p(i,l)):m.error({title:"Error",message:"Please enter a search term!"})});async function p(a,s){d.style.display="block";try{const o=await y.get("https://pixabay.com/api/",{params:{key:b,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:40}});d.style.display="none",o.data.hits.length>0?(L(o.data.hits),n.style.display="block"):m.error({title:"No Results",message:"Sorry, no images found. Please try again!"})}catch{d.style.display="none",m.error({title:"Error",message:"Something went wrong. Please try again!"})}}function L(a){const s=a.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" />
            <div class="image-info">
              <span><i class="fas fa-heart"></i> ${r.likes}</span>
              <span><i class="fas fa-eye"></i> ${r.views}</span>
              <span><i class="fas fa-comments"></i> ${r.comments}</span>
              <span><i class="fas fa-download"></i> ${r.downloads}</span>
            </div>
        </a>
    `).join("");f.innerHTML+=s,new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}n.addEventListener("click",async()=>{l++,await p(i,l)});
//# sourceMappingURL=index.js.map
