import{i as y,a as g,S as h}from"./assets/vendor-DimZQZwF.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const b=document.getElementById("search-form"),f=document.getElementById("gallery"),d=document.getElementById("loader"),w=document.querySelector(".load-more-container"),r=document.getElementById("load-more"),m=document.getElementById("end-message");r.textContent="Load more";r.style.display="none";w.appendChild(r);const I="45874849-b987a1554bc8f853b4bc2ad05";let i=1,l="",p=0;b.addEventListener("submit",async n=>{n.preventDefault(),l=document.getElementById("search-query").value.trim(),l?(i=1,f.innerHTML="",r.style.display="none",m.style.display="none",await u(l,i)):y.error({title:"Error",message:"Please enter a search term!"})});async function u(n,a){d.style.display="block";try{const o=await g.get("https://pixabay.com/api/",{params:{key:I,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",page:a,per_page:40}});if(d.style.display="none",p=o.data.totalHits,o.data.hits.length>0){L(o.data.hits),r.style.display="block",a*40>=p?(r.style.display="none",m.style.display="block"):m.style.display="none";const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}else y.error({title:"No Results",message:"Sorry, no images found. Please try again!"})}catch{d.style.display="none",y.error({title:"Error",message:"Something went wrong. Please try again!"})}}function L(n){const a=n.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item">
            <img src="${t.webformatURL}" alt="${t.tags}" />
            <div class="image-info">
              <span><i class="fas fa-heart"></i> ${t.likes}</span>
              <span><i class="fas fa-eye"></i> ${t.views}</span>
              <span><i class="fas fa-comments"></i> ${t.comments}</span>
              <span><i class="fas fa-download"></i> ${t.downloads}</span>
            </div>
        </a>
    `).join("");f.innerHTML+=a,new h(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}r.addEventListener("click",async()=>{i++,await u(l,i)});
//# sourceMappingURL=index.js.map
